digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
character = "a" ... "z" | "A" ... "Z"

(* Identifiers are the names of variables, functions, and types. *)
identifier_start = character | "_" | "$" | "?" | "!"
identifier = identifier_start + (digit | character | "_" | "$" | "?" | "!")*

(* Binary operators. *)
bin_op = "+" | "-" | "*" | "/" | "=" | "==" | "!=" | "<" | "<=" | ">" | ">=" | "&&" | "||"

(* Keywords are internal names whose meaning can not be changed. *)
kw_static = "if" | "else" | "while" | "return" | "break" | "continue" | "for" | "in" | "true" | "false" | "null"
kw_weak = "do"
kw_reserved = "static"